# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2dc09d44399322712d5848e4987881c335ff7010f5485b53aab76e265cd3b3ac878672e92d4b81542c469d1e600191767ef322e9738de523358b6c779b36db1

test:
  secret_key_base: bb52e1a3ea3419b5e9fab40b5ff0037d9b7ed92a6bfb4af6acd7143f1b06ed5e02c6a892c881669982fe6ef66b8d75647ac44c45a7b8cc0cd7405cdd995de4e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
